config/routes.rb
Rails.application.routes.draw do
  resources :characters

  resources :actors

  resources :shows

  resources :show_characters

  root to: 'roots#show'

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  has_many :characters

  has_many :shows, through: :characters

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :gender, :birth_year)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birth_year %><br>
    <%= f.number_field :birth_year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<h1>Listing actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Birth year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.gender %></td>
        <td><%= actor.birth_year %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @actor.gender %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @actor.birth_year %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>