config/routes.rb
Rails.application.routes.draw do
  resources :characters

  resources :actors

  resources :shows

  resources :show_characters

  root to: 'roots#show'

end

app/models/show.rb
class Show < ActiveRecord::Base

  has_many :show_characters
  has_many :characters, through: :show_characters

  def actors
    Actor.joins(:characters, :shows).where(shows: { id: id }).distinct
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:name, :genre, :premiere_year, :season_count, :episode_count, :running)
    end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :premiere_year %><br>
    <%= f.number_field :premiere_year %>
  </div>
  <div class="field">
    <%= f.label :season_count %><br>
    <%= f.number_field :season_count %>
  </div>
  <div class="field">
    <%= f.label :episode_count %><br>
    <%= f.number_field :episode_count %>
  </div>
  <div class="field">
    <%= f.label :running %><br>
    <%= f.check_box :running %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<h1>Listing shows</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>Premiere year</th>
      <th>Season count</th>
      <th>Episode count</th>
      <th>Running</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show.name %></td>
        <td><%= show.genre %></td>
        <td><%= show.premiere_year %></td>
        <td><%= show.season_count %></td>
        <td><%= show.episode_count %></td>
        <td><%= show.running %></td>
        <td><%= link_to 'Show', show %></td>
        <td><%= link_to 'Edit', edit_show_path(show) %></td>
        <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @show.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @show.genre %>
</p>

<p>
  <strong>Premiere year:</strong>
  <%= @show.premiere_year %>
</p>

<p>
  <strong>Season count:</strong>
  <%= @show.season_count %>
</p>

<p>
  <strong>Episode count:</strong>
  <%= @show.episode_count %>
</p>

<p>
  <strong>Running:</strong>
  <%= @show.running %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>