config/routes.rb
Rails.application.routes.draw do
  resources :characters

  resources :actors

  resources :shows

  resources :show_characters

  root to: 'roots#show'

end

app/models/show_character.rb
class ShowCharacter < ActiveRecord::Base

  belongs_to :show
  belongs_to :character

end

app/controllers/show_characters_controller.rb
class ShowCharactersController < ApplicationController
  before_action :set_show_character, only: [:show, :edit, :update, :destroy]

  # GET /show_characters
  # GET /show_characters.json
  def index
    @show_characters = ShowCharacter.all
  end

  # GET /show_characters/1
  # GET /show_characters/1.json
  def show
  end

  # GET /show_characters/new
  def new
    @show_character = ShowCharacter.new
  end

  # GET /show_characters/1/edit
  def edit
  end

  # POST /show_characters
  # POST /show_characters.json
  def create
    @show_character = ShowCharacter.new(show_character_params)

    respond_to do |format|
      if @show_character.save
        format.html { redirect_to @show_character, notice: 'Show character was successfully created.' }
        format.json { render :show, status: :created, location: @show_character }
      else
        format.html { render :new }
        format.json { render json: @show_character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /show_characters/1
  # PATCH/PUT /show_characters/1.json
  def update
    respond_to do |format|
      if @show_character.update(show_character_params)
        format.html { redirect_to @show_character, notice: 'Show character was successfully updated.' }
        format.json { render :show, status: :ok, location: @show_character }
      else
        format.html { render :edit }
        format.json { render json: @show_character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /show_characters/1
  # DELETE /show_characters/1.json
  def destroy
    @show_character.destroy
    respond_to do |format|
      format.html { redirect_to show_characters_url, notice: 'Show character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show_character
      @show_character = ShowCharacter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_character_params
      params[:show_character].permit(:show_id, :character_id)
    end
end

app/helpers/show_characters_helper.rb
module ShowCharactersHelper
end

app/views/show_characters/_form.html.erb
<%= form_for(@show_character) do |f| %>
  <% if @show_character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show_character.errors.count, "error") %> prohibited this show_character from being saved:</h2>

      <ul>
      <% @show_character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/show_characters/edit.html.erb
<h1>Editing show_character</h1>

<%= render 'form' %>

<%= link_to 'Show', @show_character %> |
<%= link_to 'Back', show_characters_path %>

app/views/show_characters/index.html.erb
<h1>Listing show_characters</h1>

<table>
  <thead>
    <tr>
      <th>Show</th>
      <th>Character</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @show_characters.each do |show_character| %>
      <tr>
        <td><%= show_character.show %></td>
        <td><%= show_character.character %></td>
        <td><%= link_to 'Show', show_character %></td>
        <td><%= link_to 'Edit', edit_show_character_path(show_character) %></td>
        <td><%= link_to 'Destroy', show_character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show character', new_show_character_path %>

app/views/show_characters/new.html.erb
<h1>New show_character</h1>

<%= render 'form' %>

<%= link_to 'Back', show_characters_path %>

app/views/show_characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Show:</strong>
  <%= @show_character.show %>
</p>

<p>
  <strong>Character:</strong>
  <%= @show_character.character %>
</p>

<%= link_to 'Edit', edit_show_character_path(@show_character) %> |
<%= link_to 'Back', show_characters_path %>